harp-tech/harp-python

pyproject.toml

This PR configures black on pyproject toml to ensure standardize code formatting rules for the project.

Add support for black code formatter

---

harp/io.py

This PR introduces the basic binary file reader which is used as the first building block in setting up high-level register readers. This reader assumes that messages are stored in flat-binary files where all messages in each file belong to a single register message, i.e. that it has a fixed message payload.
The current implementation parses the first message to understand the structure of the payload, and then reads and interprets every remaining payload in bulk.

Add single register binary file reader

---

harp/io.py
harp/reader.py
pyproject.toml

This PR introduces high-level infrastructure for automatically creating efficient register payload readers from a device metadata file. The proposed API parses an existing device schema and creates a data frame processing pipeline using function composition. Each step aims to use only efficient pandas operators so the final data extraction can be made as fast as possible.
The returned `DeviceReader` object is a dynamic collection of register readers, supporting automatic code-completion and leveraging parsed device metadata to maximize contextual exploration of device data.

Add dynamic schema-based register reader classes

---

harp/reader.py

This PR generalizes the register reader factory with support for more complex payload spec members, including arbitrary array indexing, bitwise member masks, group masks and Boolean types.

Add support for parsing payload spec members

---

MANIFEST.in
harp/common.yml
harp/model.py
harp/reader.py
harp/schema.py

This PR introduces a schema reader module to make it easier to construct full device data models from YML files. The schema reader includes support for loading built-in common registers for convenience.
For Pydantic compatibility reasons a modified YML schema of common registers is included in the package. This should be eventually replaced with a corrected version of the common YML file in the reflex-generator repo.

Add schema reader module

---

harp/io.py
tests/test_io.py

This PR extends the `read` method with support for keeping message type when reading harp binary files. The feature is implemented using [`Categorical.from_codes`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Categorical.from_codes.html) to efficiently map from raw message type values to strings.
The resulting categorical column can be compared using either names or codes in the `MessageType` enum.

Add support for keeping message type

---

harp/io.py
harp/model.py
harp/reader.py
harp/schema.py
pyproject.toml
tests/test_io.py

This PR refactors the module source to ensure successful type checking. Apart from a few minor edge cases which require further investigation (mostly operations that should be well-defined to the type checker but for some reason are not), the source is now fully annotated and validated.

Refactor modules for type checking

---

harp/io.py
harp/schema.py
tests/data/device.yml
tests/test_schema.py

This PR adds tests for the schema reader module and improves package deployment compatibility by reading the embedded common register schema using [`importlib.resources`](https://docs.python.org/3.11/library/importlib.resources.html). This is the recommended away to read embedded package resources for python 3.9+ and allows for the package to be deployed as a zip file.

Read common register schema using importlib

---

tests/data/device.yml
tests/params.py
tests/test_io.py
tests/test_reader.py
tests/test_schema.py

This PR sets up parametric testing for the `create_reader` method, with and without validation. It builds up upon the existing tests for the `schema` module with the goal of regression testing new features.

Add unit tests for reader module

---

harp/reader.py
tests/test_reader.py

This feature allows passing all optional parameters to register reader. The reader module was refactored so that all extra columns, e.g. `type` are included in the final frame after all conversion steps are applied.
For example, the below example retrieves the frame using UTC time and including the message type for all recorded messages:
```python
from harp.io import REFERENCE_EPOCH
from harp.reader import create_reader
reader = create_reader('device.harp')
reader.WhoAmI.read(epoch=REFERENCE_EPOCH, keep_type=True)
```

Add support for passing optional parameters to register reader

---

harp/reader.py
tests/test_reader.py

This feature allows setting a default reference epoch and other common params for all register readers when creating the device reader from a schema or folder, to make it easier to setup consistent data frame outputs and reduce bookkeeping.
For example, you can set a common reference epoch at the top and then get consistent time indices for all dataframes:
```python
from harp.io import REFERENCE_EPOCH
reader = create_reader('device.ylm', epoch=REFERENCE_EPOCH)
reader.WhoAmI.read()
```
It is also possible to override the parameters for individual reads, e.g. `reader.WhoAmI.read(keep_type=True)` will make the type column visible no matter what the default setting is.

Allow setting default params when creating device reader

---

harp/io.py
harp/reader.py
tests/test_io.py

In the first version of the interface there was an attempt to make naming of decoded columns match the recommended style for local variables in Python (snake_case). However, this required automatically transforming the casing of names specified in Harp schemas (typically Pascal-cased). This transformation was found to be broken in several important edge cases.
For this new release, we decided to keep the original styling of schemas, rather than attempting to fix the transformation, which will also increase consistency with the names of automatically generated Reader classes.
This PR essentially removes all casing transformations from the reader pipeline and makes column names fully aligned with device schema naming conventions. The built-in columns for time and message type were also …

Change column names to match schema casing

---

README.md
harp/__init__.py
harp/io.py
harp/reader.py
harp/schema.py

This PR surfaces the main API functions through the top-level `harp` package. The project README was also updated to summarize use of the standard data model and reference documentation included for all top-level imports.

Surface public API through top-level package

---

harp/schema.py

Pylance kept complaining about the redundant file mode and indeed the default for open is already text mode, so no need to have it here.

Remove redundant file mode

---

harp/io.py

NumPy 2.0 disallows silent overflow when converting to unsigned dtypes which was causing parsing to fail when reading timestamped registers.
This PR introduces an early explicit conversion to prevent overflow and ensure full compatibility with NumPy 1.26+ and NumPy 2.0+.
Fixes #32

Avoid silent overflow for numpy compatibility

---

.github/workflows/build.yml
harp/__init__.py
harp/reader.py
harp/schema.py
pyproject.toml

To improve the process for external code contributions, this PR adds a CI pipeline using `ruff`, `pyright` and `pytest` with preliminary support for code coverage. Badges are not generated yet but all outputs are there and a few outstanding recommendations have been applied.
Tests are run against python 3.9 and 3.11 for now on all platforms.

Add CI pipeline and code coverage

---

.github/workflows/build.yml
harp/__init__.py
harp/io.py
harp/model.py
harp/reader.py
harp/typing.py
pyproject.toml
tests/params.py
tests/test_io.py

Harp register data is commonly read from a file offline, but can also be batch loaded from in-memory buffers. This PR generalizes the device and register readers to expose a new `parse` method that works identical to `read` but receives any buffer-like object following [PEP 688](https://peps.python.org/pep-0688/).
This extends the library to be able to parse data from almost any source, including live streaming use cases.

Add support for parsing data from a memory buffer

---

.gitignore
harp/io.py
harp/schema.py
tests/test_io.py

Although the majority of common analysis use cases requires only the parsing of Harp flat binary files and messages into data frames, it is also desirable to support the converse operation: generating Harp binary files from existing data frames.
This enables post-processing and storage of processed datasets using the exact same binary format, for compatibility with existing systems. Regression tests were added to validate successful round-trip.
Further testing may be required to ensure timestamp roundtrip is not lossy if done over `float64`. Given the specs of the 8-bit protocol this should be the case, but conversion may require revision in case of the 32-bit protocol.

Allow formatting data as binary protocol messages

---

harp/io.py
tests/params.py
tests/test_io.py

When an `epoch` argument is specified on a call to `read` or `parse` the index of the resulting data frame should be of type `DatetimeIndex`, even if the data is empty.
Fixes #39

Ensure datetime index when epoch is specified

---

harp/__init__.py
harp/io.py
harp/reader.py
harp/typing.py
tests/test_io.py

Similar to other numeric and data frame processing libraries we would like to minimize the redundancy of functions exposed by the `io` module to avoid confusion.
Here we merge `read` and `parse` into a single `read` function accepting either a file-like or a buffer-like object. For consistency and symmetry, we also rename `write` and `format` as `to_file` and `to_buffer` functions, respectively.
Finally, the order of the first parameters into the `to_file` function has been swapped to match what would be more closely expected from an extension method.

Refactor IO API for consistency and symmetry

---

harp/io.py
harp/reader.py
tests/data/device.yml
tests/test_reader.py

Fixes an issue where the inner callable from ` _compose_parser` was not allowing the data input to be optional. 
https://github.com/harp-tech/harp-python/blob/9d05b584b9a16fe48fbbac89f2889b879a336ced/harp/reader.py#L79-L97
This allows `g` aka `_create_register_reader` to take care of the path inference logic
Closes #45

Make `data` input to `_compose_parser` optional
